import { expect, test } from '@playwright/test'

test('dropdowns support keyboard selection, filtering, and dismissal', async ({ page }) => {
  await page.goto('/')
  const filter = page.getByRole('combobox', { name: 'Filter by status' })
  await filter.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('option', { name: 'All statuses', exact: true })).toBeFocused()
  await page.keyboard.press('End')
  await expect(page.getByRole('option', { name: 'Completed', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(filter).toHaveText('Completed')
  await expect(page.getByRole('status').filter({ hasText: 'Showing' })).toContainText('Showing 2 of 6')
  await filter.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Showing' })).toContainText('Showing 6 of 6')
  await page.getByRole('combobox', { name: 'Status for Design the landing page', exact: true }).click()
  await page.getByRole('option', { name: 'Pending', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Status for Design the landing page', exact: true })).toHaveText('Pending')
})

test('form dropdown works inside a dialog and layouts fit the viewport', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.fonts.check('500 16px Montserrat'))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Add task', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await page.getByLabel('Title', { exact: true }).fill('Check custom dropdowns')
  await page.getByLabel('Description', { exact: true }).fill('Verify keyboard, touch, and responsive layout.')
  await page.getByRole('combobox', { name: 'Task status', exact: true }).click()
  const list = page.getByRole('listbox')
  await expect(list).toBeVisible()
  const bounds = await list.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeVisible()
  await expect(list).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Task status', exact: true }).click()
  await page.getByRole('option', { name: 'In Progress', exact: true }).click()
  await page.getByRole('button', { name: 'Create task', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('combobox', { name: 'Status for Check custom dropdowns', exact: true })).toHaveText('In Progress')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
